# -*- coding: utf-8 -*-
"""lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SsUArzGWpAGcI5GYSNm7kLhjxuWF9C6
"""

###################################################
# MC102 - Algoritmos e Programação de Computadores
# Laboratório 3 - Planejando o Final de Semana
# Nome: Gustavo Nogaroto
# RA: 280893
###################################################

# leitura de dados
orcamento = float(input())
clima = input()
tempo_livre = input()

# Verificação e impressão da atividade
if orcamento <= 500:
    if clima == 'N':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Caminhada"
        elif tempo_livre == 'A':
            atividade = "Piscina"
    elif clima == 'C':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Descansar"  # R$500 ou menos: Descansar
        elif tempo_livre == 'A':
            atividade = "Leitura"
    elif clima == 'E':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Caminhada"
        elif tempo_livre == 'A':
            atividade = "Piscina"
else:  # orcamento > 500
    if clima == 'N':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Cinema"
        elif tempo_livre == 'A':
            atividade = "Praia"
    elif clima == 'C':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Comprar um livro e realizar a leitura"  # R$600: Comprar livro
        elif tempo_livre == 'A':
            atividade = "Leitura"
    elif clima == 'E':
        if tempo_livre == 'P':
            atividade = "Descansar"
        elif tempo_livre == 'M':
            atividade = "Cinema"
        elif tempo_livre == 'A':
            atividade = "Praia"

# saída
print(atividade)