# -*- coding: utf-8 -*-
"""lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgy2EdEV64TzwQWhVLWIwjELpW7Jyqsl
"""

###################################################
# MC102 - Algoritmos e Programação de Computadores
# Laboratório 2 - Melhor Oferta
# Nome: Gustavo Nogaroto
# RA: 280893
###################################################

# Leitura da entrada

k = int(input().strip())  #Quantidade de unidades do produto que você deseja comprar (número inteiro).
P = float(input().strip())  #Preço unitário do produto (número real).
X = float(input().strip())  #Desconto percentual oferecido pela Loja A (número real).
Y = int(input().strip())  #Quantidade de produtos que você paga na promoção da Loja B (número inteiro).
Z = int(input().strip())  #Quantidade de produtos que você leva na promoção da Loja B (número inteiro).

# Cálculo do custo na Loja A

custo_a = (k * P) * (1 - X / 100)

# Cálculo do custo na Loja B

pacotes = (k + Z - 1) // Z  # Quantidade mínima de pacotes para cobrir k unidades
custo_b = pacotes * Y * P

# Comparação e saída
print(custo_a < custo_b)

#True: Caso a Loja A tenha um custo menor do que da Loja B.
#False: Caso a Loja B tenha um custo menor ou igual ao da Loja A.